map_type: costmap
transform_tolerance: 0.2
obstacle_range: 2.5
raytrace_range: 3.0
inflation_radius: 0.4 #0.25
robot_radius: 0.275
observation_sources: base_scan



base_scan: {sensor_frame: base_laser_link,
            data_type: LaserScan,
            topic: /scan,
            expected_update_rate: 0.2,
            observation_persistence: 0.0,
            marking: true,
            clearing: true,
            min_obstacle_height: -0.10,
            max_obstacle_height: 2.0}

